### ISSUE TITLE
What is the best way to connect react-query devtools to an application?

### ISSUE THREAD

**Issue by andryxxa93** [tramvaijs/tramvai#3]
If you follow the react-query [documentation](https://tanstack.com/query/latest/docs/framework/react/devtools), then in order to connect React-Query devtools, the application must be wrapped at the App level in ReactQueryDevtools. However, the App is not in the application created through the tramvai. Is there some approach to do this? There is an idea to wrap the main Layout in ReactQueryDevtools, but it seems that this is not the best option.

**Comment by SuperOleg39** [comment]
Hello!

Application pages already wrapped in `QueryClientProvider`, so I think, that you can use `ReactQueryDevtools` anywhere.

Also, you can render `ReactQueryDevtools` directrly with `client` instace from DI:

```tsx
import { useDi } from '@tramvai/react';
import { QUERY_CLIENT_TOKEN } from '@tramvai/module-react-query';

const Devtools = () => {
  const client = useDi(QUERY_CLIENT_TOKEN);
  
  return <ReactQueryDevtools client={client} />;
}
```

We have own Tramvai DevTools with React Query integration, but unfortunately for now only in private packages(

**Comment by andryxxa93** [comment]
Thanks for your answer!
