### ISSUE TITLE
Error when using updateCurrentRoute

### ISSUE THREAD

**Issue by andryxxa93** [tramvaijs/tramvai#4]
Hello! I'm trying to use updateCurrentRoute like this inside a component. I first got it from useRouter.

```tsx
      updateCurrentRoute({
        query: { a: 'string' },
      });
```

But when called it gives an error. Please tell me how to use this correctly?

![image](https://github.com/tramvaijs/tramvai/assets/60173362/cf6a92b1-89a8-4f6a-8260-f1986fd781a5)

**Comment by ereshidov** [comment]
Hello! 

I have same issue and error after using `updateCurrentRoute` from `useRouter`. We will investigate the reason and return with fix.

As a quick fix - use action to update current route without page update, here is documentation - https://tramvai.dev/docs/features/routing/links-and-navigation?_highlight=updatecurrentroute#route-update

**Comment by andryxxa93** [comment]
> Hello!
> 
> I have same issue and error after using `updateCurrentRoute` from `useRouter`. We will investigate the reason and return with fix.
> 
> As a quick fix - use action to update current route without page update, here is documentation - https://tramvai.dev/docs/features/routing/links-and-navigation?_highlight=updatecurrentroute#route-update

Hi, thanks for a quick fix) I need to update query only, so in my case i use useNavigate

**Comment by SuperOleg39** [comment]
@andryxxa93 Hello, can I ask you for complete code snippet with `updateCurrentRoute`?

It looks like you are using destucturization for Router object, and `this` context was lost.

**Comment by andryxxa93** [comment]
@SuperOleg39 yes, if i don't use destucturization - it's works fine. Thanks!
