### ISSUE TITLE
useRouter & Storybook

### ISSUE THREAD

**Issue by andryxxa93** [tramvaijs/tramvai#5]
Hello!
There is a component that uses the `useRouter` hook - it gets the `back` method from it. I'm trying to write stories for a component, but it gives me this error. I couldn’t find in the documentation what needs to be passed to the `storybook` settings to solve it.

![image](https://github.com/tramvaijs/tramvai/assets/60173362/b4dbb4fc-8e35-4c87-88eb-85bbb4f89a5a)

**Comment by andryxxa93** [comment]
In order not to create another issue, I’ll mention here that the back method from the useRouter and usePageService hooks does not return back.

**Comment by SuperOleg39** [comment]
Hello!

At first, stop to destructurize Router object, as I mention in previous issue)

And Router in storybook addon is just a simple mock:
- https://github.com/tramvaijs/tramvai/blob/main/packages/tramvai/storybook-addon/src/decorators/routerDecorator.tsx
- https://github.com/tramvaijs/tramvai/blob/main/packages/tramvai/test/mocks/src/router.ts#L18

`useRouter` can return nothing if you have a few `@tinkoff/router` copies, and Router Context object will be different in decorator and component.
You need to follow this guide - https://tramvai.dev/docs/guides/storybook

**Comment by andryxxa93** [comment]
Thanks, it's helped!
