### ISSUE TITLE
Context in react-query always has "any" type

### ISSUE THREAD

**Issue by andryxxa93** [tramvaijs/tramvai#6]
Context in react-query always has "any" type.

![image](https://github.com/user-attachments/assets/519526aa-29a0-4c24-ba02-73d984f570f9)

But in [example](https://github.com/TanStack/query/tree/main/examples/react/optimistic-updates-cache) of react-query - context automatically gets the type from the returned values in onMutate.

**Comment by SuperOleg39** [comment]
@andryxxa93 Hello!

Thanks for the report.

In tramvai query mutation wrappers, `TContext` generic is absent.

Will fix it soon!

**Comment by SuperOleg39** [comment]
Fix landed in `v3.40.57` and `v4.20.7`
