### ISSUE TITLE
Nested layout does not work on Windows because of underscore in file name

### ISSUE THREAD

**Issue by EgorPestov** [tramvaijs/tramvai#7]
When I implement a nested layout with creating '_layout.tsx' it works on Mac OCs, but on Windows I get this:
<img width="574" alt="image" src="https://github.com/user-attachments/assets/fb342481-9535-4e7a-8021-c728430b0023">

What can I do in this situation?

**Comment by ereshidov** [comment]
Fix landed in `v3.40.61` and `v4.26.0`
